complete -c fgo -f
complete -c fgo -l help -s h -d 'Show help'
complete -c fgo -l version -d 'Print version and exit'

complete -c fgo -n '__fish_use_subcommand' -f -a help -d 'Help about any command'
complete -c fgo -n '__fish_use_subcommand' -f -a updateGoVersion -d 'Upgrade Go using the workspace script'
complete -c fgo -n '__fish_use_subcommand' -f -a install-flow -d 'Install into ~/bin and optionally add it to PATH'
complete -c fgo -n '__fish_use_subcommand' -f -a commit -d 'Generate a commit message'
complete -c fgo -n '__fish_use_subcommand' -f -a commitPush -d 'Generate a commit message and push'
complete -c fgo -n '__fish_use_subcommand' -f -a commitReviewAndPush -d 'Review commit message interactively then push'
complete -c fgo -n '__fish_use_subcommand' -f -a branchFromClipboard -d 'Create a branch from the clipboard name'
complete -c fgo -n '__fish_use_subcommand' -f -a clone -d 'Clone a GitHub repository into ~/gh/<owner>/<repo>'
complete -c fgo -n '__fish_use_subcommand' -f -a cloneAndOpen -d 'Clone a GitHub repository and open it in Cursor'
complete -c fgo -n '__fish_use_subcommand' -f -a gitCheckout -d 'Check out a remote branch locally'
complete -c fgo -n '__fish_use_subcommand' -f -a version -d 'Reports the current version of fgo'

complete -c fgo -n '__fish_seen_subcommand_from help' -f -a updateGoVersion -d 'Upgrade Go using the workspace script'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a install-flow -d 'Install into ~/bin and optionally add it to PATH'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a commit -d 'Generate a commit message'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a commitPush -d 'Generate a commit message and push'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a commitReviewAndPush -d 'Review commit message interactively then push'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a branchFromClipboard -d 'Create a branch from the clipboard name'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a clone -d 'Clone a GitHub repository into ~/gh/<owner>/<repo>'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a cloneAndOpen -d 'Clone a GitHub repository and open it in Cursor'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a gitCheckout -d 'Check out a remote branch locally'
complete -c fgo -n '__fish_seen_subcommand_from help' -f -a version -d 'Reports the current version of fgo'
